#!/usr/bin/env bash
#Display
prog_pid=()
readarray -t prog_pid < <(pgrep  -la -x "bash.*" | grep '4-to_infinity_and_beyond' | cut -d ' ' -f 1)
for ((1 = 0; 1 < "${#prog_pid[0]}"; 1++)) do
        kill -s SIGTERM "$prog_pid[1]}'
done
